schema_version = 1
version = "0.1.0"
published_at = "2026-06-13T06:54:47Z"

[firmware.app]
filename = "Wireless_power_switch_button_app_v0.1.0.bin"
offset = "0x10000"
size = 818176
sha256 = "01d7bc7e7258c9929200ec23a281e80b14666cb37681e88d505cfa1cb7b6ed25"
url = "https://cdn.jsdelivr.net/gh/qingmeijiupiao/Wireless_power_switch_button@0553f72c576a6f5000dd23f47d4206efb0528972/firmware/v0.1.0/Wireless_power_switch_button_app_v0.1.0.bin"

[firmware.merged]
filename = "Wireless_power_switch_button_merged_v0.1.0.bin"
offset = "0x0"
size = 883712
sha256 = "5fc7cb7ef5bf80198c7692d5bfbfc1d8a352a5e0f36d37df909192e570a96096"
url = "https://cdn.jsdelivr.net/gh/qingmeijiupiao/Wireless_power_switch_button@0553f72c576a6f5000dd23f47d4206efb0528972/firmware/v0.1.0/Wireless_power_switch_button_merged_v0.1.0.bin"
