schema_version = 1
version = "0.2.0"
published_at = "2026-09-25T09:41:49Z"

[firmware.app]
filename = "Wireless_power_switch_button_app_v0.2.0.bin"
offset = "0x10000"
size = 818896
sha256 = "83d638f5aa5e46b6e245c79aed62aeb444582ef44e4daca0dfbf5e2d7421ef53"
url = "https://cdn.jsdelivr.net/gh/qingmeijiupiao/Wireless_power_switch_button@ffc80ddcc302ccfff7b098ae179ed4d6b36ee097/firmware/v0.2.0/Wireless_power_switch_button_app_v0.2.0.bin"

[firmware.merged]
filename = "Wireless_power_switch_button_merged_v0.2.0.bin"
offset = "0x0"
size = 884432
sha256 = "779c192925105fafdb33e890b154375f9a497e93028a92fd64fcb2306ffd981b"
url = "https://cdn.jsdelivr.net/gh/qingmeijiupiao/Wireless_power_switch_button@ffc80ddcc302ccfff7b098ae179ed4d6b36ee097/firmware/v0.2.0/Wireless_power_switch_button_merged_v0.2.0.bin"
