schema_version = 1
version = "0.3.0"
published_at = "2026-10-05T12:23:05Z"

[firmware.app]
filename = "Wireless_power_switch_button_app_v0.3.0.bin"
offset = "0x10000"
size = 833248
sha256 = "11b7dfeee8a136741c222873557aeceb4e9adbf90a9819627def03729d12c97f"
url = "https://cdn.jsdelivr.net/gh/qingmeijiupiao/Wireless_power_switch_button@6f68f7cb95b791382c3a7f5ab07227116b25b67a/firmware/v0.3.0/Wireless_power_switch_button_app_v0.3.0.bin"

[firmware.merged]
filename = "Wireless_power_switch_button_merged_v0.3.0.bin"
offset = "0x0"
size = 898784
sha256 = "74517b772d6a7beb9bd0cece3b96f673573f7467eb008506875c5a90b904cd89"
url = "https://cdn.jsdelivr.net/gh/qingmeijiupiao/Wireless_power_switch_button@6f68f7cb95b791382c3a7f5ab07227116b25b67a/firmware/v0.3.0/Wireless_power_switch_button_merged_v0.3.0.bin"
